### ISSUE TITLE
Add spaCy 3 compatibility

### ISSUE THREAD

**Issue by thedjinn** [gandersen101/spaczz#49]
Currently spaczz does not install alongside the new spaCy 3 release. Attempting to upgrade a project to spaCy 3 while also using spaczz gives the following Pip error message:

```
The conflict is caused by:
    The user requested spacy==3.0.3
    spaczz 0.4.1 depends on spacy<3.0.0 and >=2.2.0
```

**Comment by gandersen101** [comment]
Hi @thedjinn. This is definitely a high priority for me. I am wrapping up a couple small fixes/enhancements now. If adding spaCy 3.0 compatibility does not require large changes (I don't think it will) I will include the spaCy 3.0 compatibility in the next release hopefully by the end of the weekend.

**Comment by gandersen101** [comment]
I'm a little behind schedule but hoping to have this done by Wednesday.

**Comment by gandersen101** [comment]
I was able to get v3 support working today however I am struggling with how to support both v2 and v3 at the same time which would be ideal. Unfortunately, I am going to end up spending some more time on this. Thanks for your patience.

**Comment by gandersen101** [comment]
I am having trouble getting the latest release uploaded to PyPi, as there seems to be an issue over there. Hopefully it will be resolved by the end of the day. Downloading the latest release available here should work in the meantime though.
