### ISSUE TITLE
RegexMatcher: Match Captures?

### ISSUE THREAD

**Issue by karrtikiyer** [gandersen101/spaczz#64]
I am able to get this [regex](https://pythex.org/?regex=(%3Fi)proficiency%20in%20(%5B%5Cw%5Cs%5D%2B)%20tools%20like%20(.*%24)&test_string=Hello%20how%20are%20you%3F%20Proficiency%20in%20ETL%20tools%20like%20Informatica%2C%20Talend%2C%20Alteryx%20and%20Visualization%20tools%20like%20PowerBi%2C%20Tableau%20and%20Qlikview.&ignorecase=0&multiline=0&dotall=0&verbose=0) working using below code.

```
import spacy
from spaczz.matcher import RegexMatcher

nlp = spacy.blank("en")
text = "Hello how are you? Proficiency in ETL tools like Informatica, Talend, Alteryx and Visualization tools like PowerBi, Tableau and Qlikview"
doc = nlp(text)

matcher = RegexMatcher(nlp.vocab)
matcher.add(
    "SKILL",
    [
        r"""(?i)proficiency in ([\w\s]+) tools like (.*$)"""
    ],
)  
matches = matcher(doc)

for match_id, start, end, counts in matches:
    print(match_id, doc[start:end], counts)
```

And I get the matched sentence as output as expected.
However I am unsure if there is way I can get access to the match capture `([\w\s]+)` & `(.*$)`. Looking for any suggestions or advise. 
Once I get matched result/sentence, I would like to access the match captures `ETL` and `Informatica, Talend, Alteryx and Visualization tools like PowerBi, Tableau and Qlikview.`

**Comment by gandersen101** [comment]
Hi @karrtikiyer. Spaczz's regex matching essentially just extends on the spaCy's docs own recommendations for [applying regex to a full text](https://spacy.io/usage/rule-based-matching#regex-text). You can see the same ideas implemented in spaczz's `RegexSearcher.match()` method. As of now, spaczz only captures the regex match span and fuzzy counts, however it would be relatively simple to capture additional regex information and return that as well.

I have to think about whether there is a consistent way I can work regex capture data into the spaczz API. I am planning on doing a feature overhaul/upgrade on spaczz in the near future so I will keep this request in mind.

**Comment by karrtikiyer** [comment]
Thanks a lot @gandersen101
