### ISSUE TITLE
Is there a way to get back the original dictionary item that matches?

### ISSUE THREAD

**Issue by lingvisa** [gandersen101/spaczz#71]
```
NAME Grint Anderson 86
GPE Nashv1le 82
```

@gandersen101 For both 'Grint' and 'Nashv1le' are from text, and their corresponding dictionary items are "Grant Andersen" and "Nashville". Is there a way to know which dictionary item matches the text? For example, if I want to find misspellings, how do I know 'Grint' is whose misspelling?

**Comment by gandersen101** [comment]
Hi @lingvisa, sorry for the slow response. I have had minimal time to work on `spaczz` for a while now but this has been highly requested.

I can't give any guaranteed timeline on addressing this but it is on my todo list. In the meantime please see this temporary workaround: https://github.com/gandersen101/spaczz/issues/55#issuecomment-803215367.

**Comment by lingvisa** [comment]
Thanks for update. I will try the walk around first.

**Comment by Rahul-Chittora** [comment]
Hello, If I am not wrong you can add the "id" in the patterns and while 
`patterns = [
    {
        "label": "NAME",
        "pattern": "Grant Andersen",
        "type": "fuzzy",
        "kwargs": {"fuzzy_func": "token_sort"},
       "id": "Grant Andersen"
    }`
    While inferring you can use
    `
for ent in doc.ents:
    print(ent.text, ent.ent_id_)`

**Comment by gandersen101** [comment]
Hi @lingvisa, `spaczz` v0.6 now will return the pattern that was matched. Please see the latest [release notes](https://github.com/gandersen101/spaczz/blob/main/CHANGELOG.md) for some important changes to be aware of.

**Comment by gandersen101** [comment]
Closed by #81.
