### ISSUE TITLE
Installing spaczz with successful RapidFuzz installed

### ISSUE THREAD

**Issue by lorijwong** [gandersen101/spaczz#77]
Similar to another post, but it still doesn't install even after successfully installing RapidFuzz separately. 
This is what I get:
      cl : Command line warning D9025 : overriding '/W3' with '/W4'
      cpp_process.cpp
      src/cpp_process.cpp(16): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rapidfuzz
Failed to build rapidfuzz
ERROR: Could not build wheels for rapidfuzz, which is required to install pyproject.toml-based projects

**Comment by gandersen101** [comment]
@lorijwong, `spaczz` v0.6 is now tested against rapidfuzz v1-3 and Python 3.7-3.11. Please try to install the latest version of `spaczz`, and please see the latest [release notes](https://github.com/gandersen101/spaczz/blob/main/CHANGELOG.md) for some important changes to be aware of.
