### ISSUE TITLE
Update rapidfuzz

### ISSUE THREAD

**Issue by florian-sattler** [gandersen101/spaczz#80]
Currently [rapidfuzz](https://pypi.org/project/rapidfuzz/) is required in versions `>=1.0.0` and `<2.0.0` in `pyproject.toml`:
```toml
rapidfuzz = "^1"
```
however [rapidfuzz](https://pypi.org/project/rapidfuzz/) is currently available in version `2.15.1`.

This breaks other packages or installations which require a more recent version of rapidfuzz directly or indirectly.

After updating to:
```toml
rapidfuzz = ">=1.0.0"
```
all unit tests are still successful.

Is there a reason why versions 2.x are hold back?

**Comment by gandersen101** [comment]
Hi @florian-sattler, I have slowly been working through a fairly substantial update/refactor for `spaczz` but it sounds like I may need to get some parts of this update out sooner than later. I should be able to get some of the update, which will include `rapidfuzz 2.0` support, out this week. Thanks!

**Comment by gandersen101** [comment]
Hi @florian-sattler, `spaczz>=0.6` should support `rapidfuzz>=1.0` now (including the new rapidfuzz v3). Please see the latest [release notes](https://github.com/gandersen101/spaczz/blob/main/CHANGELOG.md) for some important changes to be aware of.

**Comment by florian-sattler** [comment]
Thank you very much! Works like a charm 😊
